@host = 0.0.0.0:8080

### Admin登录
# @name adminLogin
@adminAccessToken = {{adminLogin.response.body.$.data.access_token}}
@adminRefreshToken = {{adminLogin.response.body.$.data.refresh_token}}
POST http://{{host}}/user/login
Content-Type: application/json

{
   "username": "admin",
   "password": "123456"
}

### 刷新Admin Token
# @name adminRefresh
POST http://{{host}}/user/refresh
Content-Type: application/json
Authorization: {{adminAccessToken}}

{
   "refresh_token": "{{adminRefreshToken}}"
}

### test用户登录
# @name testLogin
@testAccessToken = {{testLogin.response.body.$.data.access_token}}
POST http://{{host}}/user/login
Content-Type: application/json

{
   "username": "test",
   "password": "123456"
}

### 获取Admin登录用户信息
# @name getAdminLoginUserInfo
GET http://{{host}}/user/info
Content-Type: application/json
Authorization: {{adminAccessToken}}


### 增加weijian用户
# @name addWeijianUser
@weijianUserId = {{addWeijianUser.response.body.$.data.id}}
POST http://{{host}}/user/add
Content-Type: application/json
Authorization: {{adminAccessToken}}

{
   "username": "weijian",
   "password": "123456"
}

### 修改weijian密码
# @name updateWeijianUser
PUT http://{{host}}/user/update
Content-Type: application/json
Authorization: {{adminAccessToken}}

{
   # "id": {{weijianUserId}},
   "username": "weijian",
   "old_password": "123456",
   "new_password": "1234567890",
   "new_password_repeat": "1234567890"
}

### weijian用户登录
# @name weijianLogin
@weijianToken = {{weijianLogin.response.body.$.data.access_token}}
POST http://{{host}}/user/login
Content-Type: application/json

{
   "username": "weijian",
   "password": "12345678"
}

### 删除weijian用户
DELETE http://{{host}}/user/{{weijianUserId}}
Content-Type: application/json
Authorization: {{adminAccessToken}}


### 获取菜单
GET http://{{host}}/menu/list
Content-Type: application/json
Authorization: {{adminAccessToken}}


### 增加员工
POST http://{{host}}/employee/add
Content-Type: application/json
Authorization: {{adminAccessToken}}

{
  "id": 0,
  "name": "张三",
  "gender": "男",
  "birthday": "1995-08-15T00:00:00+08:00",
  "height": 178,
  "weight": 68,
  "degree": "本科",
  "identifier": "452123198908141615",
  "phone": "13388886666",
  "political_status": "群众",
  "social_security": "有",
  "current_address": "广东省广州市天河区天景街道全天路188号",
  "first_work_time": "2018-07-01T00:00:00+08:00",
  "former_employer": "蓝盾股份",
  "post": "保安",
  "salary": 7000,
  "security_card": "88886666",
  "comments": "1) 简化流程： 设计简洁直观的操作流程；\n2) 清晰明确： 语言表达清晰且表意明确，让用户快速理解进而作出决策；\n3) 帮助用户识别： 界面简单直白，让用户快速识别而非回忆，减少用户记忆负担。",
  "updated_at": "2023-04-17T15:32:19+08:00"
}

### 模糊查询
POST http://{{host}}/employee/search
Content-Type: application/json
Authorization: {{adminAccessToken}}

{
   "key": "212"
}

### 获取岗位
GET http://{{host}}/post/list
Content-Type: application/json
Authorization: {{adminAccessToken}}
